updating ClassServiceAllRequest.cs file on develop-cs branch on 23_08_22
mngoe/rest_api_c-sharp pull request #8
Opened 2022-08-23 17:38 UTC by 20GHhub19

the file ClassService AllRequest.cs has been updated with the modification that allows the list of subservice and subItem

2022-08-23 17:57 UTC, mngoe requested changes

2022-08-23 17:57 UTC, mngoe commented on OpenImis.ModulesV2/ServiceAllModule/ClassServiceAllRequest.cs
> +                if (col == "SubService" && listcheck_id_services[1])
@20GHhub19 ca n'a aucun sens...

Donc tu fait un if listcheck_id_services[1] , tu rajoutes une colonne SubService , pui 5 lignes apres tu fait un check pour etre sur que la colonne SubService et listcheck_id_services[1] sont definis...

Des controles qui n'ont aucun sens...

2022-08-24 00:43 UTC, 20GHhub19 commented on OpenImis.ModulesV2/ServiceAllModule/ClassServiceAllRequest.cs
> +                if (col == "SubService" && listcheck_id_services[1])
@mngoe la modification a été faite et un nouveau `merge request `a été fait

2022-08-24 07:58 UTC, mngoe approved these changes

2022-08-24 07:58 UTC, merged